name: dizher
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - codecov
  - numpy
  - scipy
  - scikit-image
  - py-opencv
  - pip
  - pip:
    - pillow
    - imgui-bundle>=1.92.900
