[metadata]
name = dizher
version = attr: dizher.__version__
author = Ruguevara and Co
author_email = ruguevara@ruguevara.ru
description = Dizher (and AvtoDizher) is a 8-bit Graphics Converter for lovely retro color-restricive graphics modes.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/ruguevara/dizher
project_urls =
    Bug Tracker = https://github.com/ruguevara/dizher/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
include_package_data = True
install_requires =
    numpy
    scipy
    scikit-image
    opencv-python
    numba
    imageio
    FreeSimpleGUI

[options.packages.find]
where = src

[options.package_data]
* = *.txt, *.png, *.yml

[options.entry_points]
console_scripts =
    dizher = dizher.gui.__main__:main
