[metadata]
name = dizher
version = attr: dizher.__version__
author = Ruguevara and Co
author_email = ruguevara@ruguevara.ru
description = Dizher (and AvtoDizher): an image converter for 8-bit computers with colour-restricted graphics modes, such as the ZX Spectrum and the Commodore 64.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/ruguevara/dizher
project_urls =
    Bug Tracker = https://github.com/ruguevara/dizher/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.11
include_package_data = True
install_requires =
    numpy
    scipy
    scikit-image
    opencv-python
    imageio
    pillow
    imgui-bundle>=1.92.900

[options.packages.find]
where = src

[options.package_data]
* = *.txt, *.png, *.yml

[tool:pytest]
testpaths = tests

[options.entry_points]
console_scripts =
    dizher = dizher.ui.__main__:main
